name: Lint with Ruff

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install Ruff
        run: |
          python -m venv venv  # Create a virtual environment
          . venv/bin/activate  # Activate the virtual environment
          pip install ruff     # Install Ruff

      - name: Run Ruff Linter
        run: |
          . venv/bin/activate  # Activate the virtual environment
          ruff check .               # Run Ruff on the entire project
